test profiles first pass

diff --git a/procedures/automatic b/procedures/automatic
--- a/procedures/automatic
+++ b/procedures/automatic
@@ -1015,10 +1015,12 @@ OFFinstallpkg() {
         
         for package in $ALL_PACKAGES
         do
-            if [[ `pacman -Q "^$package$" &>/dev/null` ]]; then
+            if [[ `$PACMAN_TARGET -Q "^$package$" &>/dev/null` ]]; then
                 inform "INSTALLATION: $package already installed; skipping"
-            elif `pacman -Ss "^$package$" &>/dev/null`
+                dpause
+            elif `$PACMAN_TARGET -Ss "^$package$" &>/dev/null`
             then
+                echo "about to install.... xyz"; dpause
                 run_controlled pacman_installpkg "$PACMAN_TARGET --noconfirm -S $package" $TMP_PACMAN_LOG "Installing $package..." 
             elif [[ -n "$var_AUR_SUPPORT" ]]
             then
@@ -1045,3 +1047,46 @@ OFFinstallpkg() {
 
         return $CONTROLLED_EXIT
 }
+
+ORIGinstallpkg() {
+        ALL_PACKAGES=
+        [ -n "$var_TARGET_GROUPS" ] && ALL_PACKAGES=`list_packages group "$var_TARGET_GROUPS" | awk '{print $2}'`
+        if [ -n "$var_TARGET_PACKAGES_EXCLUDE" ]
+        then
+                for excl in $var_TARGET_PACKAGES_EXCLUDE
+                do
+                        ALL_PACKAGES=${ALL_PACKAGES//$excl/}
+                done
+        fi
+
+        if [ -n "$var_TARGET_PACKAGES" ]
+        then
+                [ -n "$ALL_PACKAGES" ] && ALL_PACKAGES="$ALL_PACKAGES $var_TARGET_PACKAGES"
+                [ -z "$ALL_PACKAGES" ] && ALL_PACKAGES=$var_TARGET_PACKAGES
+        fi
+        ALL_PACKAGES=`echo $ALL_PACKAGES`
+        [ -z "$ALL_PACKAGES" ] && die_error "No packages/groups specified to install"
+
+        target_special_fs on
+
+        notify "Package installation will begin now.  You can watch the output in the progress window. Please be patient."
+
+        run_controlled pacman_installpkg "$PACMAN_TARGET --noconfirm -S $ALL_PACKAGES" $TMP_PACMAN_LOG "Installing... Please Wait" 
+
+        local _result=''
+        if [ $CONTROLLED_EXIT -ne 0 ]; then
+                _result="Installation Failed (see errors below)"
+                echo -e "\nPackage Installation FAILED." >>$TMP_PACMAN_LOG
+        else
+                _result="Installation Complete"
+                echo -e "\nPackage Installation Complete." >>$TMP_PACMAN_LOG
+        fi
+
+        show_warning "$_result" "$TMP_PACMAN_LOG" text || return 1
+
+        target_special_fs off
+        sync
+
+        return $CONTROLLED_EXIT
+}
+
