dirty tests

diff --git a/procedures/automatic b/procedures/automatic
--- a/procedures/automatic
+++ b/procedures/automatic
@@ -491,7 +491,7 @@ make_local ()
     local full_path_remote=$1
 
     # check repo type
-    local repo_type=$(detect_repo_type "$full_path_remote") || die_error "Unexpected error detected repository type from $full_path_remote"
+    local repo_type=$(detect_repo_type "$full_path_remote") && echo "REPO TYPE SET TO $repo_type" || die_error "Unexpected error detected repository type from $full_path_remote"
 
     # now set the repo clone command, infix to strip out github/bitbucket raw file path values, and any suffix required to clone (.git)
     local repo_command=
