dirty tests

diff --git a/procedures/automatic b/procedures/automatic
--- a/procedures/automatic
+++ b/procedures/automatic
@@ -823,10 +823,10 @@ config_switch ()
     fi
     case $method in
         set|add)
-            $target_function set $file_path $target_value $*  && ( inform "value \"$target_value\" set to \"$*\" in $file_path"; return 0 )  || ( echo "IN A"; show_warning "CONFIG FAILURE" "FAILED $target_value $method $*"; return 1 )
+            $target_function set $file_path $target_value $*  && ( inform "CONFIG SUCCESS: value \"$target_value\" set to \"$*\" in $file_path"; return 0 )  || ( echo "IN A"; show_warning "CONFIG FAILURE" "FAILED $target_value $method $*"; return 1 )
         ;;
         unset|remove|delete)
-            "$target_function" unset $file_path $target_value $* && ( inform "value \"$target_value\" removed from $file_path"; return 0 ) || ( echo "IN B"; show_warning "CONFIG FAILURE" "FAILED $target_value $method $*"; return 1 )
+            "$target_function" unset $file_path $target_value $* && ( inform "CONFIG SUCCESS: value \"$target_value\" removed from $file_path"; return 0 ) || ( echo "IN B"; show_warning "CONFIG FAILURE" "FAILED $target_value $method $*"; return 1 )
         ;;
     esac
 }
