dirty dirty testing...

diff --git a/procedures/automatic b/procedures/automatic
--- a/procedures/automatic
+++ b/procedures/automatic
@@ -245,7 +245,8 @@ worker_select_source ()
 worker_write_configs()
 {
     inform "Configuration write started"
-    dfunc; for config_command in $CONFIG_CHANGES; do $config_command || echo "FAILED $config_command"; done
+    echo $CONFIG_CHANGES >> /tmp/ccdump.txt
+    dfunc; for config_command in $CONFIG_CHANGES; do $config_command || echo "WWC FAILED $config_command"; done
 
 }
 
@@ -664,6 +665,7 @@ config_switch ()
         unset|remove|delete) "$target_function" unset $file_path $target_value $* && inform "$target_value UNSET: $*" || show_warning "FAILED $target_value UNSET: $*" ;;
     esac
 }
+
 kernel_parameter_write()
 {
     # TODO: identify bootloader?
